title: Miker
email:
description: "Personal Blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rowehl.com" # the base hostname & protocol for your site, e.g. http://example.com

navbar-links:
  About: "about"
  TipJar: "https://publishers.basicattentiontoken.org/en/c/miker"

rss-description: "Mike Rowehl's personal blog"

social-network-links:
  rss: true
  github: mikerowehl
  twitter: miker
  mastodon: mastodon.social/@mikerowehl

# Build settings
theme: beautiful-jekyll-theme
include:
  - .well-known

avatar: "/assets/images/avatar.png"
favicon: "/assets/images/favicon.ico"
paginate: 10
show_excerpts: true

gtag: G-L5N0TL16L4

plugins:
  - jekyll-feed
